## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
env:
    - ARCH=x86_64
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
# before_script: # homebrew for mac
#   - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

before_deploy:
  - tar -cvzf libvaxdata-$ARCH-$TRAVIS_OS_NAME.tar.gz $TRAVIS_BUILD_DIR/deps/usr/lib/libvaxdata-$ARCH-*

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  api_key:
    secure: "p9r/RpauCA9ASc9J2ZxngFufHHPuGXnIRXRvAhiHvbYifes/Pgq40Wsj4igsfhJjHhkkCISD3RWmW1k/Ka+GcZVijYIuK5c7wTCIK4/HJgRBcQ0qq/L/7fCHS0nBFNcSWf2+QjWtHGQ40n3uNPaZDv6ZQBXfMVFhaSYTcnjcyON3GBhnLSSupHY+cOZ1Mf5r6iVwFkhQi5kbLroGeaLvU9tyLCJ7zP2OsSjymxSKGY34NHZADktXYWAjylahfaWDvKbpFs8UcQDdJRsgrlSQ/s4t2RSju0sut9K3iy+GRNNqmwiXwPSCFvKTIzuA0tg6S15fXQdfOChCMeUpt+wQjo81aZUGAeCcCJk2+eHv/qdgatFgm4klP3w2fHHC0dAUpoWug0tkzx3fqOBtur1USwVMlKYFi+R126jbkLklqT0DHkA7jextMLbHsrKVVjAy6dErIuNUAtbeIe25qSVXS680q2P0bbpg18Hs2Qd+I8q4dfICdMjeO2HDnt495hugEugvlA5QRaPVSySrVlBEsL+IGJ/xvaW13Yk/S5Y5DQkUfgbi+HKG2nbcAriHAtzl0JiSdwm61r4YhiphOKwUkMQcJphnFPwjuvAlpluWhIRBpK2UqIGQBiAVv82g9Y6JCr0AkYKxHNzNFA477nKsW2c22rCWk2rCiN9hxtGWpi8="
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/libvaxdata-x86_64-*.tar.gz"
  skip_cleanup: true
  draft: true
  on:
    condition: "$TRAVIS_ALLOW_FAILURE = false"
    tags: true

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("C3D"); Pkg.test("C3D"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("C3D")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
