name = "C3D"
uuid = "2f289508-6d0e-11e8-2c47-b9ffa24fd0e3"
authors = ["Allen Hill <allenofthehills@gmail.com>"]
version = "0.2.0"

[deps]
VaxData = "a6f58a78-e649-57e2-81bc-1d865c7b74f7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"] 

